### ISSUE TITLE
Slurm and Munge user UIDs

### ISSUE THREAD

**Issue by zachsnoek** [zachsnoek/slurm17-centos7#2]
If they are to be the same across all of the nodes, then they shouldn't be created randomly. Add variables in the script for specific UIDs; onus is on the administrator to make sure they are open.

**Comment by joemathai** [comment]
hi Zach, thanks for the script to setup slurm. I have a few questions,
1. why do one have to setup slurm and a munge user?
2. Should the slurmctld and slurmd service be launched as slurm user?
3. Is there a reason you are omitting the setup of slurmdbd?
